name: 'Deploy to Nomad'
description: 'Deploy docker image to nomad.'
author: 'Toeverything'
inputs:
  job-id:
    required: true
    description: 'Job id'
  image-url:
    required: true
    description: 'Docker image url'
  static-port:
    required: true
    description: 'Static port'
  container-port:
    required: true
    description: 'Container port'
  nomad-domain:
    required: true
    description: 'Nomad domain'

runs:
  using: 'node16'
  main: 'dist/index.js'
